server:
  port: 80



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

mybatis:
  mapper-locations: mapper/**/**.xml
  config-location: mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    kr:
      co:
        biztax:
          nordic:
            repository: trace